/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/books/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Books
         * @description List all books that have been uploaded.
         */
        get: operations["list_books_api_books__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload And Estimate
         * @description Upload an EPUB and get a cost estimate before processing.
         *
         *     The EPUB is saved and ingested. Returns chapter/paragraph counts
         *     and a token estimate so the user can decide whether to proceed.
         */
        post: operations["upload_and_estimate_api_books_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Book
         * @description Get book metadata and NCM status.
         */
        get: operations["get_book_api_books__book_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/chapters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Chapters
         * @description Get the ingested chapters with paragraph text.
         *
         *     Typed at the route boundary with ``response_model=ChaptersData`` so the HTTP
         *     contract is the structured shape. The store stays data-faithful (returns the
         *     raw dict, no model round-trip — D15); validation/serialization happens here.
         */
        get: operations["get_chapters_api_books__book_id__chapters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/chapters/{chapter_idx}/scenes/{scene_idx}/crossfade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check Crossfade
         * @description Check whether a crossfade should occur when transitioning to this scene.
         *
         *     Returns the hysteresis decision based on emotion clusters (Decision 12). The
         *     current scene is resolved via dependencies (book_id/chapter_idx/scene_idx are
         *     declared inside them and FastAPI caches the single NCM load); the previous
         *     scene stays a lenient in-body lookup.
         */
        get: operations["check_crossfade_api_books__book_id__chapters__chapter_idx__scenes__scene_idx__crossfade_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/chapters/{chapter_idx}/scenes/{scene_idx}/track": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scene Track
         * @description Get the matched music track for a scene.
         *
         *     Args:
         *         book_id: Book identifier.
         *         chapter_idx: Chapter index (matches NCM chapter_index).
         *         scene_idx: Scene index within the chapter.
         *         previous_track_id: Track currently playing (for variety rule).
         *         exclude: Comma-separated track IDs to skip (user-skipped tracks).
         *         detailed: If true, include dev metadata (candidates, scores, vectors).
         *         style: Style preset name (auto, cinematic, piano_only, ambient, synthwave, noir_jazz).
         */
        get: operations["get_scene_track_api_books__book_id__chapters__chapter_idx__scenes__scene_idx__track_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/images/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Image
         * @description Generate an on-demand image from selected text (Decision 5).
         *
         *     Injects character physical descriptions via string matching (Decision 9).
         *     Stores character memory on single-character images (Decision 8).
         */
        post: operations["generate_image_api_books__book_id__images_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/images/scene": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Scene
         * @description Generate (or return cached) scene image from the LLM-produced image_prompt (Decision 33).
         */
        post: operations["generate_scene_api_books__book_id__images_scene_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/ncm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ncm
         * @description Get the complete NCM for a book.
         */
        get: operations["get_ncm_api_books__book_id__ncm_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Process Book
         * @description Start processing a previously uploaded book. Streams progress via SSE.
         *
         *     Args:
         *         max_chapters: If set, only process this many narrative chapters (for testing/free-tier).
         *         force: If true, delete existing NCM and reprocess.
         */
        post: operations["process_book_api_books__book_id__process_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/music/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Presets
         * @description Return available music style presets with descriptions.
         */
        get: operations["list_presets_api_music_presets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_and_estimate_api_books_upload_post */
        Body_upload_and_estimate_api_books_upload_post: {
            /** File */
            file: string;
        };
        /**
         * BookMap
         * @description LLM 1 output: book-level context.
         */
        BookMap: {
            /**
             * Book Id
             * @default
             */
            book_id: string;
            /** Chapters */
            chapters?: components["schemas"]["ChapterSummary"][];
            /** Characters */
            characters?: components["schemas"]["Character"][];
            /**
             * Genre
             * @default
             */
            genre: string;
            setting?: components["schemas"]["BookSetting"];
            /**
             * Title
             * @default
             */
            title: string;
        };
        /**
         * BookResponse
         * @description The NCM-derived fields are present only once a book has been processed;
         *     they are set/unset together and dropped via response_model_exclude_unset.
         */
        BookResponse: {
            /** Book Id */
            book_id: string;
            /** Chapter Count */
            chapter_count?: number | null;
            /** Character Count */
            character_count?: number | null;
            /** Genre */
            genre?: string | null;
            /** Has Ncm */
            has_ncm: boolean;
            /** Scene Count */
            scene_count?: number | null;
            /** Title */
            title?: string | null;
        };
        /** BookSetting */
        BookSetting: {
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Time Period
             * @default
             */
            time_period: string;
            /**
             * World
             * @default
             */
            world: string;
        };
        /** BookSummary */
        BookSummary: {
            /** Book Id */
            book_id: string;
            /** Has Ncm */
            has_ncm: boolean;
            /** Title */
            title: string;
        };
        /** Chapter */
        Chapter: {
            /** Chapter Index */
            chapter_index: number;
            /**
             * Is Narrative
             * @default true
             */
            is_narrative: boolean;
            /** Paragraphs */
            paragraphs?: components["schemas"]["Paragraph"][];
            /**
             * Title
             * @default
             */
            title: string;
        };
        /**
         * ChapterAnalysis
         * @description LLM 2 output: scene-level analysis for one chapter.
         */
        ChapterAnalysis: {
            /**
             * Attempt Count
             * @default 0
             */
            attempt_count: number;
            /** Chapter Index */
            chapter_index: number;
            /**
             * Cover Description
             * @default
             */
            cover_description: string;
            /**
             * Is Fallback
             * @default false
             */
            is_fallback: boolean;
            /**
             * Llm Model
             * @default
             */
            llm_model: string;
            /** Scenes */
            scenes?: components["schemas"]["Scene"][];
        };
        /** ChapterSummary */
        ChapterSummary: {
            /** Chapter Index */
            chapter_index: number;
            /**
             * Summary
             * @default
             */
            summary: string;
            /**
             * Title
             * @default
             */
            title: string;
        };
        /**
         * ChaptersData
         * @description Ingestion output: structured text extracted from EPUB.
         */
        ChaptersData: {
            /** Chapters */
            chapters?: components["schemas"]["Chapter"][];
        };
        /** Character */
        Character: {
            /** Aliases */
            aliases?: string[];
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Physical Description
             * @default
             */
            physical_description: string;
            /** Relationships */
            relationships?: components["schemas"]["Relationship"][];
            /** @default minor */
            role: components["schemas"]["CharacterRole"];
        };
        /**
         * CharacterRole
         * @enum {string}
         */
        CharacterRole: "protagonist" | "antagonist" | "secondary" | "minor";
        /** CostEstimate */
        CostEstimate: {
            /** Book Id */
            book_id: string;
            /** Estimated Tokens */
            estimated_tokens: number;
            /** Message */
            message: string;
            /** Narrative Chapters */
            narrative_chapters: number;
            /** Total Chapters */
            total_chapters: number;
            /** Total Paragraphs */
            total_paragraphs: number;
        };
        /**
         * CrossfadeResponse
         * @description ``reason`` is set only on the short-circuit paths; the emotion/cluster
         *     fields are set only when both scenes are present (mutually exclusive).
         */
        CrossfadeResponse: {
            /** Current Cluster */
            current_cluster?: string | null;
            current_emotion?: components["schemas"]["Emotion"] | null;
            /** Previous Cluster */
            previous_cluster?: string | null;
            previous_emotion?: components["schemas"]["Emotion"] | null;
            /** Reason */
            reason?: string | null;
            /** Should Crossfade */
            should_crossfade: boolean;
        };
        /**
         * DetailedSceneTrackResponse
         * @description Dev-view projection (``detailed=True``). ``scene_vector`` is omitted when
         *     there is no candidate pool, preserving the historical no-vector shape.
         */
        DetailedSceneTrackResponse: {
            /** Candidates */
            candidates: components["schemas"]["SceneTrackCandidate"][];
            /** Fallback */
            fallback: string;
            /** Scene Vector */
            scene_vector?: number[] | null;
            /** Score */
            score: number;
            /** Selected Track */
            selected_track: string | null;
            /** Style Applied */
            style_applied: string | null;
        };
        /**
         * Emotion
         * @enum {string}
         */
        Emotion: "joy" | "sorrow" | "tension" | "anger" | "peace" | "romance" | "mystery" | "excitement" | "wonder";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImageGenerateRequest */
        ImageGenerateRequest: {
            /** Chapter Index */
            chapter_index?: number | null;
            /** Scene Index */
            scene_index?: number | null;
            /** Selected Text */
            selected_text: string;
        };
        /** MusicPreset */
        MusicPreset: {
            /** Description */
            description: string;
            /** Name */
            name: string;
        };
        /**
         * NCM
         * @description Complete Narrative Context Map for a book.
         */
        NCM: {
            book_map: components["schemas"]["BookMap"];
            /** Chapters */
            chapters?: components["schemas"]["ChapterAnalysis"][];
        };
        /** OnDemandImageResponse */
        OnDemandImageResponse: {
            /** Cache Url */
            cache_url?: string | null;
            /** Content Type */
            content_type: string;
            /** Image Base64 */
            image_base64: string;
        };
        /**
         * Pacing
         * @enum {string}
         */
        Pacing: "slow" | "medium" | "fast";
        /** Paragraph */
        Paragraph: {
            /** Index */
            index: number;
            /** Text */
            text: string;
        };
        /** Relationship */
        Relationship: {
            /** Target Id */
            target_id: string;
            /** Type */
            type: string;
        };
        /** Scene */
        Scene: {
            /** Characters Present */
            characters_present?: string[];
            emotion: components["schemas"]["Emotion"];
            /** End Paragraph */
            end_paragraph: number;
            /**
             * Image Prompt
             * @default
             */
            image_prompt: string;
            /** Key Objects */
            key_objects?: string[];
            /** Key Phrases */
            key_phrases?: string[];
            /** @default medium */
            pacing: components["schemas"]["Pacing"];
            /** Raw Emotion */
            raw_emotion?: string | null;
            /** Raw Pacing */
            raw_pacing?: string | null;
            /** Raw Scene Type */
            raw_scene_type?: string | null;
            /** Raw Transition Type */
            raw_transition_type?: string | null;
            /** Scene Index */
            scene_index: number;
            /** @default description */
            scene_type: components["schemas"]["SceneType"];
            setting?: components["schemas"]["SceneSetting"];
            /** Start Paragraph */
            start_paragraph: number;
            /**
             * Title
             * @default
             */
            title: string;
            /** @default none */
            transition_type: components["schemas"]["TransitionType"];
        };
        /** SceneImageRequest */
        SceneImageRequest: {
            /** Chapter Index */
            chapter_index: number;
            /** Scene Index */
            scene_index: number;
        };
        /** SceneImageResponse */
        SceneImageResponse: {
            /** Cache Url */
            cache_url: string;
            /** Generated */
            generated: boolean;
        };
        /** SceneSetting */
        SceneSetting: {
            /**
             * Location
             * @default
             */
            location: string;
            /**
             * Time Of Day
             * @default
             */
            time_of_day: string;
            /**
             * Weather
             * @default
             */
            weather: string;
        };
        /** SceneTrackCandidate */
        SceneTrackCandidate: {
            /** Score */
            score: number;
            /** Tags */
            tags: string[];
            /** Track Id */
            track_id: string;
        };
        /** SceneTrackResponse */
        SceneTrackResponse: {
            /** Cached */
            cached: boolean;
            /** Duration Seconds */
            duration_seconds: number;
            emotion_primary: components["schemas"]["Emotion"];
            /** File Path */
            file_path: string;
            /** Stream Url */
            stream_url: string;
            /** Tags */
            tags: string[];
            /** Track Id */
            track_id: string;
        };
        /**
         * SceneType
         * @enum {string}
         */
        SceneType: "action" | "dialogue" | "description" | "introspection" | "transition";
        /**
         * TransitionType
         * @enum {string}
         */
        TransitionType: "none" | "time_jump" | "pov_change" | "flashback" | "location_change";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_books_api_books__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["BookSummary"][];
                    };
                };
            };
        };
    };
    upload_and_estimate_api_books_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_and_estimate_api_books_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostEstimate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_book_api_books__book_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chapters_api_books__book_id__chapters_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChaptersData"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_crossfade_api_books__book_id__chapters__chapter_idx__scenes__scene_idx__crossfade_get: {
        parameters: {
            query?: {
                prev_chapter_idx?: number | null;
                prev_scene_idx?: number | null;
            };
            header?: never;
            path: {
                book_id: string;
                chapter_idx: number;
                scene_idx: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrossfadeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scene_track_api_books__book_id__chapters__chapter_idx__scenes__scene_idx__track_get: {
        parameters: {
            query?: {
                previous_track_id?: string | null;
                exclude?: string | null;
                detailed?: boolean;
                style?: string | null;
            };
            header?: never;
            path: {
                book_id: string;
                chapter_idx: number;
                scene_idx: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SceneTrackResponse"] | components["schemas"]["DetailedSceneTrackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_image_api_books__book_id__images_generate_post: {
        parameters: {
            query?: never;
            header?: {
                "x-provider-image"?: string | null;
                "x-api-key-image"?: string | null;
            };
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImageGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnDemandImageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_scene_api_books__book_id__images_scene_post: {
        parameters: {
            query?: never;
            header?: {
                "x-provider-image"?: string | null;
                "x-api-key-image"?: string | null;
            };
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SceneImageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SceneImageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ncm_api_books__book_id__ncm_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NCM"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    process_book_api_books__book_id__process_post: {
        parameters: {
            query?: {
                max_chapters?: number | null;
                force?: boolean;
            };
            header: {
                "x-provider-llm": string;
                "x-api-key-llm": string;
            };
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_presets_api_music_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MusicPreset"][];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
